<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
  <title>SELECT  * FROM `vbulletin_user`
</title>
  <meta name="GENERATOR" content="HeidiSQL 3.0 Revision: 572">
  <style type="text/css"><!--
    .header {background-color: ActiveCaption; color: CaptionText;}
    th {vertical-align: top;}
    td {vertical-align: top;}
  --></style>
</head>

<body>

<h3>SELECT  * FROM `vbulletin_user`
 (3 Records)</h3>

<table border="1">
  <tr class="header">
    <th>userid</th>
    <th>usergroupid</th>
    <th>membergroupids</th>
    <th>displaygroupid</th>
    <th>username</th>
    <th>password</th>
    <th>passworddate</th>
    <th>email</th>
    <th>styleid</th>
    <th>parentemail</th>
    <th>homepage</th>
    <th>icq</th>
    <th>aim</th>
    <th>yahoo</th>
    <th>msn</th>
    <th>skype</th>
    <th>showvbcode</th>
    <th>showbirthday</th>
    <th>usertitle</th>
    <th>customtitle</th>
    <th>joindate</th>
    <th>daysprune</th>
    <th>lastvisit</th>
    <th>lastactivity</th>
    <th>lastpost</th>
    <th>lastpostid</th>
    <th>posts</th>
    <th>reputation</th>
    <th>reputationlevelid</th>
    <th>timezoneoffset</th>
    <th>pmpopup</th>
    <th>avatarid</th>
    <th>avatarrevision</th>
    <th>profilepicrevision</th>
    <th>sigpicrevision</th>
    <th>options</th>
    <th>birthday</th>
    <th>birthday_search</th>
    <th>maxposts</th>
    <th>startofweek</th>
    <th>ipaddress</th>
    <th>referrerid</th>
    <th>languageid</th>
    <th>emailstamp</th>
    <th>threadedmode</th>
    <th>autosubscribe</th>
    <th>pmtotal</th>
    <th>pmunread</th>
    <th>salt</th>
    <th>ipoints</th>
    <th>infractions</th>
    <th>warnings</th>
    <th>infractiongroupids</th>
    <th>infractiongroupid</th>
    <th>adminoptions</th>
  </tr>
  <tr>
    <td>1&nbsp;</td>
    <td>6&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>Tuxi&nbsp;</td>
    <td>0f933105a9930872350306b4736d6d72&nbsp;</td>
    <td>2007-07-01&nbsp;</td>
    <td>abc@abc.de&nbsp;</td>
    <td>0&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2&nbsp;</td>
    <td>2&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1183304718&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1183305017&nbsp;</td>
    <td>1183305017&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>10&nbsp;</td>
    <td>1&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>2135&nbsp;</td>
    <td>&nbsp;</td>
    <td>0000-00-00&nbsp;</td>
    <td>-1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>-1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>UC(&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
  </tr>
  <tr>
    <td>2&nbsp;</td>
    <td>3&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>Test&nbsp;</td>
    <td>2c5a8ed823291bc73aff8ae081a1ff06&nbsp;</td>
    <td>2007-07-01&nbsp;</td>
    <td>abcd@abcd.de&nbsp;</td>
    <td>0&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2&nbsp;</td>
    <td>0&nbsp;</td>
    <td>Neuer Benutzer&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1183305366&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1183305366&nbsp;</td>
    <td>1183306119&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>10&nbsp;</td>
    <td>5&nbsp;</td>
    <td>1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>7383&nbsp;</td>
    <td>&nbsp;</td>
    <td>0000-00-00&nbsp;</td>
    <td>-1&nbsp;</td>
    <td>2&nbsp;</td>
    <td>127.0.0.1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>y&lt;|&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
  </tr>
  <tr>
    <td>3&nbsp;</td>
    <td>3&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>testtest&nbsp;</td>
    <td>60b355d082d081bf14c0d6862518c08b&nbsp;</td>
    <td>2007-07-07&nbsp;</td>
    <td>test@test.de&nbsp;</td>
    <td>0&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2&nbsp;</td>
    <td>0&nbsp;</td>
    <td>Neuer Benutzer&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1183805187&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1183805187&nbsp;</td>
    <td>1183805204&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>10&nbsp;</td>
    <td>5&nbsp;</td>
    <td>1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>7383&nbsp;</td>
    <td>&nbsp;</td>
    <td>0000-00-00&nbsp;</td>
    <td>-1&nbsp;</td>
    <td>2&nbsp;</td>
    <td>127.0.0.1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>1&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>!I=&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
    <td>&nbsp;</td>
    <td>0&nbsp;</td>
    <td>0&nbsp;</td>
  </tr>
</table>

<p>
<em>generated 2007-07-07 12:49:03 by <a href="http://www.heidisql.com/">HeidiSQL 3.0 Revision: 572</a></em></p>

</body></html>